select * from customer limit 200

ALTER TABLE customer
CHANGE COLUMN `Purchase Amount (USD)` Purchase_Amount FLOAT;

DESCRIBE customer;

--Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(Purchase_Amount) as revenue
from customer
group by gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount?

select `customer id`, purchase_amount
from customer
where `discount applied`= 'Yes' 
and purchase_amount >= (
select AVG (purchase_amount) 
from customer
);


--Q3. Which are the top 5 products with the highest average review rating?
select `Item Purchased`,round(avg(`review rating`),2)as "average product rating"
from customer
group by `item purchased`
order by avg(`review rating`) desc
limit 5;

select `Item Purchased`,avg(`review rating`) as "average product rating"
from customer
group by `item purchased`
order by avg(`review rating`) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select `shipping type`,round(avg (Purchase_Amount),2) as "average Purchase Amounts"
from customer
where `shipping type` in ('Standard','Express')
group by `shipping type`;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between > subscribers and non-subscribers.
select `Subscription Status`,
count(`customer id`)as total_customers,
round(avg (Purchase_Amount),2) as avg_spend,
round(sum(Purchase_Amount),2) as total_revenue
from customer
group by `Subscription Status`
order by total_revenue,avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select `Item Purchased`,
round(100 * sum(case when `Discount Applied`='yes' then 1 else 0 end)/count(*) ,2) as discount_rate
from customer
group by `Item Purchased`
order by discount_rate desc
limit 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total 
--number of previous purchases, and show the count of each segment.
with customer_type as(
select `Customer ID`,`Previous Purchases`,
case when `Previous Purchases` = 1 then 'new'
when `Previous Purchases` between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment


--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
`Item Purchased`,
count(`Customer ID`) as total_orders,
row_number() over(partition by category order by count(`Customer ID`) DESC) AS item_rank
from customer
group by `Category`,`Item Purchased`
)
select item_rank,category,`Item Purchased`,total_orders
from item_counts
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select `subscription status`,
count(`customer id`) as repeat_buyers
from customer
where `previous purchases` > 5
group by `subscription status`

--Q10. What is the revenue contribution of each age group?
select Age,sum(purchase_amount) as total_revenue
from customer
group by age
order by total_revenue desc;

SELECT * FROM customer limit 5000;
